name: Build operator and push image

on:
  push:
    paths:
      - /operator

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: RyanSiu1995/kubebuilder-action@v1.1
      - run: make test
      - uses: docker/setup-buildx-action@v1
      - name: Extract tag name
        id: tag
        run: |
          printenv
          TAG=$(echo "${GITHUB_REF}" | sed 's/\/?refs\/(tags|heads)\///g' -E)
          echo "TAG=$TAG" | tee -a $GITHUB_ENV
      - name: Login
        uses: docker/login-action@v1.6.0
        with:
          username: joeshearn
          password: ${{ secrets.dockerhub_pass }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.1
        with:
          context: operator
          tags: joeshearn/github-runner-autoscaler-operator:${{ env.TAG }},joeshearn/github-runner-autoscaler-operator:latest
          push: ${GITHUB_REF == "master"}
