kind: ActionRunnerMetrics
apiVersion: runner.devjoes.com/v1alpha1
metadata:
  name: main
spec:
  name: github-metrics-apiserver
  namespace: runners
  existingSslCertSecret: cert
  image: "joeshearn/github-runner-autoscaler-apiserver:master"
  prometheusNamespace: default
