apiVersion: v2
name: github-runner-registration
description: Operator for github-runner-registration
home: https://github.com/devjoes/github-runner-autoscaler/
sources:
  - https://github.com/devjoes/github-runner-autoscaler
type: application
version: 0.1.1
appVersion: v0.1.0
