apiVersion: v1
entries:
  github-runner-autoscaler:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-04-27T15:50:26.5893809+01:00"
    description: Operator for github-runner-autoscaler
    digest: 7efabe1140afd0c6b43b510d105dd85ab15f59c7551aca3047e5c024b8bd55bb
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-04-27T15:50:26.5891379+01:00"
    description: Operator for github-runner-autoscaler
    digest: 58d8ca52b599fe8089c07c29428a784ee8a7857ba55a630f954dab15cec3eca3
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2021-04-27T15:50:26.5888506+01:00"
    description: Operator for github-runner-autoscaler
    digest: c538e602565cb0f219af404095360f06ad00021d3349f6533b70ca500f482162
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2021-04-27T15:50:26.5886054+01:00"
    description: Operator for github-runner-autoscaler
    digest: ed06f0a1d99ce9701fc4ad6141367ae02c8f4e3ccafb8704e6ff74b39af37476
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2021-04-27T15:50:26.5883572+01:00"
    description: Operator for github-runner-autoscaler
    digest: 87a82032cb33a00c8c82371bc4f38c3e36214e04c4d293001e3337f7523dc86e
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2021-04-27T15:50:26.5881035+01:00"
    description: Operator for github-runner-autoscaler
    digest: 72ffc9839628c3e01cbcff3e6ffb9c0fb6fbf8188ffa69304190b9c998e9ecc0
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2021-04-27T15:50:26.587828+01:00"
    description: Operator for github-runner-autoscaler
    digest: e3348b73715c646a3b15b0c2a3d9e91f2bfe8c359f12e5bdc68ac865bb64dd35
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2021-04-27T15:50:26.5875787+01:00"
    description: Operator for github-runner-autoscaler
    digest: c88a9b945fc8151d4b0043e4461295282024956d07acf6fbac11bb2962bf420a
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2021-04-27T15:50:26.5872716+01:00"
    description: Operator for github-runner-autoscaler
    digest: 40b27d246e96d90903a229b85d8048e9c2d6518269fc64566645200786daff3d
    home: https://github.com/devjoes/github-runner-autoscaler
    name: github-runner-autoscaler
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-autoscaler-0.0.1.tgz
    version: 0.0.1
  github-runner-registration:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-04-27T15:50:26.5895257+01:00"
    description: Operator for github-runner-registration
    digest: d539d4832a5ee97845c75229b4a12c27e1c35bba611fee78747bba7b3d10de4f
    home: https://github.com/devjoes/github-runner-autoscaler/
    name: github-runner-registration
    sources:
    - https://github.com/devjoes/github-runner-autoscaler
    type: application
    urls:
    - https://devjoes.github.io/github-runner-autoscaler/charts/github-runner-registration-0.1.1.tgz
    version: 0.1.1
generated: "2021-04-27T15:50:26.5868296+01:00"
