name: deploy

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: [self-hosted, deploy]

    steps:
      - uses: actions/checkout@v2
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "test_image:latest"
      - run: echo "'Deploying' on $HOST @ $(date)"
      - run: docker run -it "test_image:latest"
