# permissions for end users to edit actionrunnermetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actionrunnermetrics-editor-role
rules:
- apiGroups:
  - runner.devjoes.com
  resources:
  - actionrunnermetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runner.devjoes.com
  resources:
  - actionrunnermetrics/status
  verbs:
  - get
