# permissions for end users to view scaledactionrunnercore.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaledactionrunnercore-viewer-role
rules:
  - apiGroups:
      - runner.devjoes.com
    resources:
      - scaledactionrunnercore
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - runner.devjoes.com
    resources:
      - scaledactionrunnercore/status
    verbs:
      - get
