
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runner.devjoes.com
  resources:
  - actionrunnermetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runner.devjoes.com
  resources:
  - actionrunnermetrics/finalizers
  verbs:
  - update
- apiGroups:
  - runner.devjoes.com
  resources:
  - actionrunnermetrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runner.devjoes.com
  resources:
  - scaledactionrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runner.devjoes.com
  resources:
  - scaledactionrunners/finalizers
  verbs:
  - update
- apiGroups:
  - runner.devjoes.com
  resources:
  - scaledactionrunners/status
  verbs:
  - get
  - patch
  - update
