kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "github-runner-registration.fullname" . }}
  labels:
    app: {{ template "github-runner-registration.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "github-runner-registration.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "github-runner-registration.name" . }}
      annotations:
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
