# permissions for end users to view scaledobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-scaledobject-viewer-role
rules:
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects/status
    verbs:
      - get
