name: build

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: [self-hosted, build]

    steps:
      - uses: actions/checkout@v2
      - run: echo "Building @ $(date)"
      - run: docker build . -t 'test_image:latest' --build-arg APP_NAME=$GITHUB_REPOSITORY --build-arg BUILD_HOST=$HOST
      - run: echo "Build finished @ $(date)"
      - run: echo "Exiting @ $(date)"
